"""02_add_model

Revision ID: 1b3374b61cda
Revises: 568975ee3a98
Create Date: 2023-05-31 23:08:08.822273

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1b3374b61cda'
down_revision = '568975ee3a98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('History',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('client', sa.String(), nullable=True),
    sa.Column('click_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['URLs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('History')
    # ### end Alembic commands ###
