"""02_rm_rel

Revision ID: 2b23b2f24172
Revises: 1b3374b61cda
Create Date: 2023-06-01 00:58:44.738755

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2b23b2f24172'
down_revision = '1b3374b61cda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
